# Generated by Django 4.0.1 on 2022-01-16 20:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='small.png', upload_to='')),
                ('AHAT', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=12)),
                ('ASAT', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=12)),
                ('FATT', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('FG', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('FCI', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('CAH', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=12)),
                ('CAP', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('APL', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_portfolio', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('asset_amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tx_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='CMApp.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='CMApp.portfolio'),
        ),
    ]
