# Generated by Django 3.2.8 on 2021-10-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('fiat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset', models.DecimalField(decimal_places=8, max_digits=12)),
                ('price_avg', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('tracked_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='journal', serialize=False, to='CMApp.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='CMApp.portfolio'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMApp.journal')),
            ],
        ),
    ]
