# Generated by Django 3.2.8 on 2021-10-21 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='fiat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
