# Generated by Django 4.0.1 on 2022-01-20 05:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0002_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset_cap_upon_creation',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
