# Generated by Django 3.2.8 on 2021-10-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0003_auto_20211021_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='credit', max_length=6),
        ),
    ]
