# Generated by Django 3.2.8 on 2021-10-25 19:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0004_entry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price_of_asset',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
