# Generated by Django 3.2.8 on 2021-11-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0007_asset_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(default='btc_default.jpg', height_field=1280, upload_to='', width_field=720),
        ),
    ]
