# Generated by Django 3.2.8 on 2021-11-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0008_alter_asset_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(default='btc_default.jpg', upload_to=''),
        ),
    ]
