# Generated by Django 3.2.8 on 2021-11-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0009_alter_asset_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, default='btc_default.jpg', height_field='image_height', help_text='Asset Image', null=True, upload_to='media', verbose_name='Asset Image', width_field='image_width'),
        ),
    ]
