# Generated by Django 3.2.8 on 2021-11-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0010_auto_20211109_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, default='small.png', height_field='image_height', help_text='Asset Image', null=True, upload_to='media', verbose_name='Asset Image', width_field='image_width'),
        ),
    ]
