# Generated by Django 3.2.8 on 2021-11-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0012_auto_20211109_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(default='small.png', upload_to='media'),
        ),
    ]
