# Generated by Django 3.2 on 2021-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0015_alter_asset_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(default='small.png', upload_to=''),
        ),
    ]
