# Generated by Django 3.2.8 on 2021-12-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0016_alter_asset_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_sold',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='fiat_made',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_avg_sold',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
