# Generated by Django 3.2.8 on 2021-11-27 23:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMApp', '0016_alter_asset_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_sold',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='asset',
            name='fiat_made',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_avg_sold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
